module.exports = Object.freeze({
     MAX_PLAYERS : 10,
     MIN_PLAYERS : 5,
     POWER_EXAMINE_TOP_3 : 'examine_top_3',
     POWER_KILL : 'kill',
     POWER_KILL_VETO : 'kill_veto',
     POWER_PICK_PRESIDENT : 'pick_president',
     POWER_EXAMINE_MEMBERSHIP : 'examine_membership',
     LIBERAL : 'liberal',
     FASCIST : 'fascist',
     PRESIDENT : 'president',
     CHANCELLOR : 'chancellor',
     CHANCELLOR_ELECT : 'chancellor_elect',
     SESSION_INIT : 'init',
     SESSION_PRESIDENCY : 'presidency',
     SESSION_ELECTION_PRIMARY : 'election_primary',
     SESSION_ELECTION_GENERAL : 'election_general',
     SESSION_LEGISLATION_PRESIDENT : 'legislation_president',
     SESSION_LEGISLATION_CHANCELLOR : 'legislation_chancellor',
     SESSION_OVER : 'over',
     VOTE_YES : 'yes',
     VOTE_NO : 'no',
});


